# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bd58014169d2eeac380aca811a8f885e99e8a072855cdd9ee942f0f46525374bcf2de1f036df0e09d1cd227a5853706d543d92c4ff6798a78315296b055da49

test:
  secret_key_base: 9a7bdf63da471578e9692b86fa760f2205848a09bcbea4591feef70c2c69732115df4a7efd91535b46dddb67b5edbc3b56a390224ac59f142c7cc474e5c767aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
